// char a[8];
// bool result = false;
// result = string_substring_idx(a, 8, "booomrumfak", 0, 3);
// log_info("%s %d", a, result);
// result = string_substring_idx(a, 8, "booomrumfak", 0, -1);
// log_info("%s %d", a, result);
// result = string_substring_idx(a, 8, "booomrumfak", 0, -2);
// log_info("%s %d", a, result);
// result = string_substring_idx(a, 8, "booomrumfak", 8, -1);
// log_info("%s %d", a, result);
// result = string_substring_idx(a, 8, "boomroo", 0, -1);
// log_info("%s %d", a, result);
// result = string_substring_idx(a, 8, "boomroo", 0, -2);
// log_info("%s %d", a, result);
// result = string_substring_idx(a, 8, "boomroo", -1, -2);
// log_info("%s %d", a, result);
// result = string_substring_idx(a, 8, "boomroo", -3, -1);
// log_info("%s %d", a, result);
